# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messages.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/messages.proto\x12\x07syncp2p\"\x8c\x01\n\x10\x44iscoveryMessage\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x11\n\tpeer_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x03 \x03(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12+\n\tendpoints\x18\x05 \x03(\x0b\x32\x18.syncp2p.NetworkEndpoint\"E\n\x0fNetworkEndpoint\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x10\n\x08protocol\x18\x03 \x01(\t\"\x91\x01\n\x13ICECandidateMessage\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x11\n\tcandidate\x18\x02 \x01(\t\x12\x0f\n\x07sdp_mid\x18\x03 \x01(\t\x12\x18\n\x10sdp_m_line_index\x18\x04 \x01(\x05\x12\x19\n\x11username_fragment\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\"\xb1\x01\n\x11ICEControlMessage\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32&.syncp2p.ICEControlMessage.MessageType\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"A\n\x0bMessageType\x12\t\n\x05OFFER\x10\x00\x12\n\n\x06\x41NSWER\x10\x01\x12\r\n\tCANDIDATE\x10\x02\x12\x0c\n\x08\x43OMPLETE\x10\x03\"\x9b\x01\n\x14\x43RDTOperationMessage\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x16\n\x0eoperation_type\x18\x02 \x01(\t\x12\x19\n\x11operation_payload\x18\x03 \x01(\x0c\x12\x19\n\x11logical_timestamp\x18\x04 \x01(\x03\x12\x0f\n\x07peer_id\x18\x05 \x01(\t\x12\x13\n\x0bparent_hash\x18\x06 \x01(\t\"\xd0\x01\n\x10\x43RDTStateMessage\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x42\n\rstate_vectors\x18\x02 \x03(\x0b\x32+.syncp2p.CRDTStateMessage.StateVectorsEntry\x12\x32\n\x0bpending_ops\x18\x03 \x03(\x0b\x32\x1d.syncp2p.CRDTOperationMessage\x1a\x33\n\x11StateVectorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CRDTSTATEMESSAGE_STATEVECTORSENTRY']._options = None
  _globals['_CRDTSTATEMESSAGE_STATEVECTORSENTRY']._serialized_options = b'8\001'
  _globals['_DISCOVERYMESSAGE']._serialized_start=34
  _globals['_DISCOVERYMESSAGE']._serialized_end=174
  _globals['_NETWORKENDPOINT']._serialized_start=176
  _globals['_NETWORKENDPOINT']._serialized_end=245
  _globals['_ICECANDIDATEMESSAGE']._serialized_start=248
  _globals['_ICECANDIDATEMESSAGE']._serialized_end=393
  _globals['_ICECONTROLMESSAGE']._serialized_start=396
  _globals['_ICECONTROLMESSAGE']._serialized_end=573
  _globals['_ICECONTROLMESSAGE_MESSAGETYPE']._serialized_start=508
  _globals['_ICECONTROLMESSAGE_MESSAGETYPE']._serialized_end=573
  _globals['_CRDTOPERATIONMESSAGE']._serialized_start=576
  _globals['_CRDTOPERATIONMESSAGE']._serialized_end=731
  _globals['_CRDTSTATEMESSAGE']._serialized_start=734
  _globals['_CRDTSTATEMESSAGE']._serialized_end=942
  _globals['_CRDTSTATEMESSAGE_STATEVECTORSENTRY']._serialized_start=891
  _globals['_CRDTSTATEMESSAGE_STATEVECTORSENTRY']._serialized_end=942
# @@protoc_insertion_point(module_scope)
