# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multi.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'multi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmulti.proto\x12\x04sync\"\xe8\x01\n\x08\x45nvelope\x12\x0f\n\x07\x66rom_id\x18\x01 \x01(\t\x12\x0e\n\x06seq_no\x18\x02 \x01(\x04\x12!\n\x04type\x18\x03 \x01(\x0e\x32\x13.sync.Envelope.Type\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\r\n\x05token\x18\x05 \x01(\t\"x\n\x04Type\x12\t\n\x05\x44\x45LTA\x10\x00\x12\x0c\n\x08PULL_REQ\x10\x01\x12\r\n\tPULL_RESP\x10\x02\x12\n\n\x06\x44IGEST\x10\x03\x12\x10\n\x0cSNAPSHOT_REQ\x10\x04\x12\x11\n\rSNAPSHOT_RESP\x10\x05\x12\x06\n\x02HB\x10\x06\x12\x0f\n\x0bPEER_ADVERT\x10\x07\"\x1d\n\x0b\x44\x65ltaBundle\x12\x0e\n\x06\x64\x65ltas\x18\x01 \x03(\x0c\"\x1d\n\x0bPullRequest\x12\x0e\n\x06\x63ursor\x18\x01 \x01(\x0c\"2\n\x0cPullResponse\x12\x0e\n\x06\x64\x65ltas\x18\x01 \x03(\x0c\x12\x12\n\nnew_cursor\x18\x02 \x01(\x0c\"&\n\x06\x44igest\x12\n\n\x02vv\x18\x01 \x01(\x0c\x12\x10\n\x08\x63hecksum\x18\x02 \x01(\x0c\"\x11\n\x0fSnapshotRequest\"$\n\x10SnapshotResponse\x12\x10\n\x08snapshot\x18\x01 \x01(\x0c\"+\n\tHeartbeat\x12\x0f\n\x07\x66rom_id\x18\x01 \x01(\t\x12\r\n\x05ts_ms\x18\x02 \x01(\x04\"8\n\x04Peer\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12\x11\n\tlast_seen\x18\x03 \x01(\x04\"8\n\nPeerAdvert\x12\x0f\n\x07\x66rom_id\x18\x01 \x01(\t\x12\x19\n\x05peers\x18\x02 \x03(\x0b\x32\n.sync.Peerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=22
  _globals['_ENVELOPE']._serialized_end=254
  _globals['_ENVELOPE_TYPE']._serialized_start=134
  _globals['_ENVELOPE_TYPE']._serialized_end=254
  _globals['_DELTABUNDLE']._serialized_start=256
  _globals['_DELTABUNDLE']._serialized_end=285
  _globals['_PULLREQUEST']._serialized_start=287
  _globals['_PULLREQUEST']._serialized_end=316
  _globals['_PULLRESPONSE']._serialized_start=318
  _globals['_PULLRESPONSE']._serialized_end=368
  _globals['_DIGEST']._serialized_start=370
  _globals['_DIGEST']._serialized_end=408
  _globals['_SNAPSHOTREQUEST']._serialized_start=410
  _globals['_SNAPSHOTREQUEST']._serialized_end=427
  _globals['_SNAPSHOTRESPONSE']._serialized_start=429
  _globals['_SNAPSHOTRESPONSE']._serialized_end=465
  _globals['_HEARTBEAT']._serialized_start=467
  _globals['_HEARTBEAT']._serialized_end=510
  _globals['_PEER']._serialized_start=512
  _globals['_PEER']._serialized_end=568
  _globals['_PEERADVERT']._serialized_start=570
  _globals['_PEERADVERT']._serialized_end=626
# @@protoc_insertion_point(module_scope)
