# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crdt.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncrdt.proto\"\x9a\x01\n\rCRDTOperation\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12&\n\x0eoperation_type\x18\x02 \x01(\x0e\x32\x0e.OperationType\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x19\n\x11logical_timestamp\x18\x04 \x01(\x04\x12\x0f\n\x07peer_id\x18\x05 \x01(\t\x12\x13\n\x0bparent_hash\x18\x06 \x01(\t*3\n\rOperationType\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crdt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OPERATIONTYPE']._serialized_start=171
  _globals['_OPERATIONTYPE']._serialized_end=222
  _globals['_CRDTOPERATION']._serialized_start=15
  _globals['_CRDTOPERATION']._serialized_end=169
# @@protoc_insertion_point(module_scope)
