# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sync.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from p2p.proto import crdt_pb2 as crdt__pb2



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsync.proto\x12\x04sync\x1a\ncrdt.proto\"6\n\x12VersionVectorEntry\x12\x0f\n\x07site_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x04\":\n\rVersionVector\x12)\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x18.sync.VersionVectorEntry\"`\n\x06\x44igest\x12\x1f\n\x02vv\x18\x01 \x01(\x0b\x32\x13.sync.VersionVector\x12\x10\n\x08op_count\x18\x02 \x01(\x04\x12\r\n\x05\x62loom\x18\x03 \x01(\x0c\x12\x14\n\x0c\x61pprox_bytes\x18\x04 \x01(\r\"Z\n\x0c\x44\x65ltaRequest\x12&\n\twant_from\x18\x01 \x01(\x0b\x32\x13.sync.VersionVector\x12\x11\n\tmax_bytes\x18\x02 \x01(\r\x12\x0f\n\x07max_ops\x18\x03 \x01(\r\"7\n\nDeltaChunk\x12\x1b\n\x03ops\x18\x01 \x03(\x0b\x32\x0e.CRDTOperation\x12\x0c\n\x04last\x18\x02 \x01(\x08\"\x16\n\x03\x41\x63k\x12\x0f\n\x07\x66or_msg\x18\x01 \x01(\t\"\xcd\x01\n\x08\x45nvelope\x12\x0e\n\x06msg_id\x18\x01 \x01(\t\x12\x0c\n\x04\x66rom\x18\x02 \x01(\t\x12\x0c\n\x04room\x18\x03 \x01(\t\x12\x1e\n\x06\x64igest\x18\n \x01(\x0b\x32\x0c.sync.DigestH\x00\x12\'\n\tdelta_req\x18\x0b \x01(\x0b\x32\x12.sync.DeltaRequestH\x00\x12\'\n\x0b\x64\x65lta_chunk\x18\x0c \x01(\x0b\x32\x10.sync.DeltaChunkH\x00\x12\x18\n\x03\x61\x63k\x18\r \x01(\x0b\x32\t.sync.AckH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sync_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERSIONVECTORENTRY']._serialized_start=32
  _globals['_VERSIONVECTORENTRY']._serialized_end=86
  _globals['_VERSIONVECTOR']._serialized_start=88
  _globals['_VERSIONVECTOR']._serialized_end=146
  _globals['_DIGEST']._serialized_start=148
  _globals['_DIGEST']._serialized_end=244
  _globals['_DELTAREQUEST']._serialized_start=246
  _globals['_DELTAREQUEST']._serialized_end=336
  _globals['_DELTACHUNK']._serialized_start=338
  _globals['_DELTACHUNK']._serialized_end=393
  _globals['_ACK']._serialized_start=395
  _globals['_ACK']._serialized_end=417
  _globals['_ENVELOPE']._serialized_start=420
  _globals['_ENVELOPE']._serialized_end=625
# @@protoc_insertion_point(module_scope)
